#!/bedrock/libexec/busybox sh
# shellcheck disable=SC2154 disable=SC2034

# shellcheck source=src/slash-bedrock/share/common-code
. /bedrock/share/common-code

Alpine="${color_distro}Alpine${color_norm}"
apk="${color_cmd}apk${color_norm}"
apt="${color_cmd}apt${color_norm}"
Arch="${color_distro}Arch${color_norm}"
bash="${color_cmd}bash${color_norm}"
Bedrock="${color_bedrock}Bedrock${color_norm}"
bedrock="${color_strat}bedrock${color_norm}"
bedrock_conf="${color_file}bedrock.conf${color_norm}"
bedrock_etc_bedrock_conf="${color_file}/bedrock/etc/bedrock.conf${color_norm}"
Bedrock_Linux="${color_bedrock}Bedrock Linux${color_norm}"
bedrock_strata="${color_file}/bedrock/strata/${color_norm}"
brl="${color_cmd}brl${color_norm}"
brl_apply="${color_cmd}brl apply${color_norm}"
brl_fetch="${color_cmd}brl fetch${color_norm}"
brl_remove="${color_cmd}brl remove${color_norm}"
brl_tutorial="${color_cmd}brl tutorial${color_norm}"
brl_which="${color_cmd}brl which${color_norm}"
cross="${color_term}cross${color_norm}"
Debian="${color_distro}Debian${color_norm}"
disable="${color_term}disable${color_norm}"
disabled="${color_term}disabled${color_norm}"
enable="${color_term}enable${color_norm}"
enabled="${color_term}enabled${color_norm}"
etc_apt_sources_list="${color_file}/etc/apt/sources.list${color_norm}"
global="${color_term}global${color_norm}"
hashbang="${color_cmd}#!/bin/sh${color_norm}"
hijack="${color_term}hijack${color_norm}"
hijacked="${color_term}hijacked${color_norm}"
home="${color_file}/home${color_norm}"
init_stratum="${color_strat}$(brl deref init)${color_norm}"
jo="${color_cmd}jo${color_norm}"
jq="${color_cmd}jq${color_norm}"
local="${color_term}local${color_norm}"
locally="${color_term}locally${color_norm}"
ls="${color_cmd}ls${color_norm}"
makepkg="${color_cmd}makepkg${color_norm}"
man="${color_cmd}man${color_norm}"
pinned="${color_term}pinned${color_norm}"
pinning="${color_term}pinning${color_norm}"
pmm="${color_cmd}pmm${color_norm}"
reboot="${color_cmd}reboot${color_norm}"
restrict="${color_term}restrict${color_norm}"
restriction="${color_term}restriction${color_norm}"
run="${color_file}/run${color_norm}"
show="${color_term}show${color_norm}"
sources_list="${color_file}sources.list${color_norm}"
strat="${color_cmd}strat${color_norm}"
Strata="${color_term}Strata${color_norm}"
strata="${color_term}strata${color_norm}"
stratum="${color_term}stratum${color_norm}"
sudo="${color_cmd}sudo${color_norm}"
tmp="${color_file}/tmp${color_norm}"
tut_alpine="${color_strat}tut-alpine${color_norm}"
tut_void="${color_strat}tut-void${color_norm}"
Ubuntu="${color_distro}Ubuntu${color_norm}"
Void="${color_distro}Void${color_norm}"
xbps_install="${color_cmd}xbps-install${color_norm}"

# Users have complained busybox mktemp output is too difficult to type when
# following tutorial instructions.  Attempt to generate a more user friendly
# temporary file names.
n=0
tmpfile=""
while true; do
	n=$((n + 1))
	tmpfile="/tmp/tut${n}"
	touch "${tmpfile}" || continue
	exec 9>"${tmpfile}" || continue
	flock -nx 9 && break
done
tmpfile2=""
while true; do
	n=$((n + 1))
	tmpfile2="/tmp/tut${n}"
	touch "${tmpfile2}" || continue
	exec 8>"${tmpfile2}" || continue
	flock -nx 8 && break
done
echo "" >"${tmpfile}"
echo "" >"${tmpfile2}"
trap 'rm -f ${tmpfile} ${tmpfile2}' INT TERM EXIT
