#!/bedrock/libexec/busybox sh
#
# run-lock
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2015 Daniel Thau <danthau@bedrocklinux.org>
#
# Some distros seem to expect /run/lock to exist on boot and will not create it
# if it is missing.  Since other distros clear /run out across reboots, this
# discrepancy can cause problems.

if ! [ -e /bedrock/strata/$1/run/lock ]
then
	mkdir /bedrock/strata/$1/run/lock
fi
return 0
