#!/bedrock/libexec/busybox sh
#
# setup-etc
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2015 Daniel Thau <danthau@bedrocklinux.org>
#
# This script will set up required Bedrock /etc files

abort() {
	echo "$@" >&2
	exit 1
}

stratum=$1
if [ "$(bri -a $stratum)" = "$(bri -a init)" ]
then
	stratum_root=""
else
	stratum_root="/bedrock/strata/$stratum"
fi

if ! [ -d "$stratum_root/etc" ]
then
	mkdir -p "$stratum_root/etc" || abort "Unable to setup /etc for $stratum"
fi

if [ ! -r "$stratum_root/etc/bedrock_stratum" ] || [ "$(cat "$stratum_root/etc/bedrock_stratum")" != "$stratum" ]
then
	echo "$stratum" > "$stratum_root/etc/bedrock_stratum" || abort "Unable to setup /etc for $stratum"
	chmod 644 "$stratum_root/etc/bedrock_stratum" || abort "Unable to setup /etc for $stratum"
fi

if [ -e /bedrock/etc/localtime ] && [ "$(sha1sum /bedrock/etc/localtime)" != "$(sha1sum $stratum_root/etc/localtime 2>/dev/null)" ]
then
	cp /bedrock/etc/localtime "$stratum_root/etc/localtime" || abort "Unable to setup /etc for $stratum"
fi

if [ -e /bedrock/etc/adjtime ] && [ "$(sha1sum /bedrock/etc/adjtime)" != "$(sha1sum $stratum_root/etc/adjtime 2>/dev/null)" ]
then
	cp /bedrock/etc/adjtime "$stratum_root/etc/adjtime" || abort "Unable to setup /etc for $stratum"
fi

if [ -e $stratum_root/lib/systemd/systemd ] && [ ! -e $stratum_root/etc/systemd/system/multi-user.target.wants/ ]
then
	mkdir -p $stratum_root/etc/systemd/system/multi-user.target.wants/
fi
