#!/bedrock/bin/busybox sh
#
# force-symlinks
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2012-2014 Daniel Thau <danthau@bedrocklinux.org>
#
# This script will create symlinks in Bedrock Linux clients just before they are setup.

create_symlinks() {
	# ensure the directories that should contain both the source and destination exist.
	mkdir -p $core_src_dir
	mkdir -p $core_dst_dir

	if [ -h $core_src ] && [ "$(readlink $core_src)" = "$client_dst" ]
	then
		# This is the desired situation, everything is already set up.
		return
	elif [ -h $core_src ] && [ "$(readlink $core_src)" != "$client_dst" ]
	then
		# The symlink exists but it is pointing in the wrong location.  This is
		# a particularly bad situation as there is no way this could have
		# happened that the script knows about.
		ln -sf "$client_dst" "$core_src"
	elif [ ! -e "$core_src" ]
	then
		# Nothing exists at where we want the symlink.  Just create it.
		ln -sf "$client_dst" "$core_src"
	elif [ -e "$core_src" ]
	then
		# Something exists at the location where we want the symlink that isn't
		# a symlink.  This is the situation for which this script was made.
		# Move that file/directory to where we want it to go, then create the
		# symlink to it.
		mv "$core_src" "core_dst"
		ln -sf "$client_dst" "$core_src"
	fi
}

client=$1

# Install the /var/lib/dbus/machine-id -> /etc/machine-id symlink

# This is where the core sees the location the symlink file will be placed.
core_src=/bedrock/clients/$client/var/lib/dbus/machine-id
core_src_dir=/bedrock/clients/$client/var/lib/dbus
# This is where the core sees the location to which the symlink will point
core_dst=/bedrock/clients/$client/etc/machine-id
core_dst_dir=/bedrock/clients/$client/etc/
# This is where the client sees the location to which the symlink will point.
client_dst=/bedrock/clients/$client/etc/machine-id

create_symlinks


# Install the /var/run -> /run symlink

# This is where the core sees the location the symlink file will be placed.
core_src=/bedrock/clients/$client/var/run
core_src_dir=/bedrock/clients/$client/var/
# This is where the core sees the location to which the symlink will point
core_dst=/bedrock/clients/$client/run
core_dst_dir=/bedrock/clients/$client/
# This is where the client sees the location to which the symlink will point.
client_dst=/run

create_symlinks

# Install the /etc/mtab -> /proc/mounts

# This is where the core sees the location the symlink file will be placed.
core_src=/bedrock/clients/$client/etc/mtab
core_src_dir=/bedrock/clients/$client/etc
# This is where the core sees the location to which the symlink will point
core_dst=/bedrock/clients/$client/proc/mounts
core_dst_dir=/bedrock/clients/$client/proc
# This is where the client sees the location to which the symlink will point.
client_dst=/proc/mounts

# we don't want to actually move an existing /etc/mtab, just delete it:
[ -e $core_src ] && rm -rf $core_src >/dev/null 2>&1

create_symlinks
