#!/bedrock/libexec/busybox awk -f
#
# Package Manager Manager pacman support script
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2013-2020 Daniel Thau <danthau@bedrocklinux.org>

#
# `pacman -S --asexplicit` is used because `pacman -S` retains
# explicit/implicit tracking on reinstalls.  Without `--asexplicit`, attempts
# to force a package to be explicitly installed by installing it would fail if
# it is already installed as a dependency.
#

system_package_managers["pacman"]
package_manager_canary_executables["pacman"] = "pacman"

#
# General, operation independent flags.
#
# Unlike operations, flags should not have implementations[].
#
user_interfaces["pacman", "assume-no"]  = ""
user_interfaces["pacman", "assume-yes"] = "--noconfirm"
user_interfaces["pacman", "confirm"]    = ""
user_interfaces["pacman", "quiet"]      = "-q/--quiet"
user_interfaces["pacman", "verbose"]    = "-v/--verbose"

#
# Operations which directly forward the underlying command output.
#
user_interfaces["pacman", "install-packages"]         = "pmm -S/--sync <pkgs>"
user_interfaces["pacman", "reinstall-packages"]       = "" # not differentiated from install
user_interfaces["pacman", "remove-packages-limited"]  = "pmm -R/--remove <pkgs>"
user_interfaces["pacman", "remove-packages-full"]     = "pmm -R/--remove -n/--nosave <pkgs>"
user_interfaces["pacman", "verify-packages"]          = "pmm -Q/--query -k/--check <pkgs>"
user_interfaces["pacman", "verify-all-packages"]      = "pmm -Q/--query -k/--check"
user_interfaces["pacman", "mark-packages-explicit"]   = "pmm -D/--database --asexplicit <pkgs>"
user_interfaces["pacman", "mark-packages-implicit"]   = "pmm -D/--database --asdeps <pkgs>"
user_interfaces["pacman", "show-package-information"] = "pmm -S/--sync -i/--info <pkgs>"
user_interfaces["pacman", "clear-cache"]              = "pmm -S/--sync -c/--clean"
user_interfaces["pacman", "remove-orphans"]           = "" # no user facing command
user_interfaces["pacman", "update-package-database"]  = "" # no separate file database concept, uses combine
user_interfaces["pacman", "update-file-database"]     = "pmm -F/--files -y/--refresh"
user_interfaces["pacman", "upgrade-packages-limited"] = "" # no partial upgrade concept
user_interfaces["pacman", "upgrade-packages-full"]    = "pmm -S/--sync -u/--sysupgrade"

implementations["pacman", "install-packages"]         = "strat -r ${stratum} pacman ${flags} -S --asexplicit ${items}"
implementations["pacman", "reinstall-packages"]       = "strat -r ${stratum} pacman ${flags} -S ${items}"
implementations["pacman", "remove-packages-limited"]  = "strat -r ${stratum} pacman ${flags} -R ${items}"
implementations["pacman", "remove-packages-full"]     = "strat -r ${stratum} pacman ${flags} -Rn ${items}"
implementations["pacman", "verify-packages"]          = "strat -r ${stratum} pacman ${flags} -Qk ${items}"
implementations["pacman", "verify-all-packages"]      = "strat -r ${stratum} pacman ${flags} -Qk"
implementations["pacman", "mark-packages-explicit"]   = "strat -r ${stratum} pacman ${flags} -D --asexplicit ${items}"
implementations["pacman", "mark-packages-implicit"]   = "strat -r ${stratum} pacman ${flags} -D --asdeps ${items}"
implementations["pacman", "show-package-information"] = "strat -r ${stratum} pacman ${flags} -Si ${items}"
implementations["pacman", "clear-cache"]              = "strat -r ${stratum} pacman ${flags} -Sc ${items}"
implementations["pacman", "remove-orphans"]           = "! strat -r ${stratum} pacman -Qdtq >/dev/null || strat -r ${stratum} pacman -Qdtq | strat -r ${stratum} pacman ${flags} -Rs -"
implementations["pacman", "update-package-database"]  = "strat -r ${stratum} pacman ${flags} -Sy"
implementations["pacman", "update-file-database"]     = "strat -r ${stratum} pacman ${flags} -Fy"
implementations["pacman", "upgrade-packages-limited"] = "strat -r ${stratum} pacman ${flags} -Su"
implementations["pacman", "upgrade-packages-full"]    = "strat -r ${stratum} pacman ${flags} -Su"

#
# Combine operations.
#
user_interfaces["pacman", "clear-cache,remove-orphans"]                                                             = ""
user_interfaces["pacman", "mark-packages-implicit,remove-orphans"]                                                  = ""
user_interfaces["pacman", "remove-packages-limited,remove-orphans"]                                                 = "pmm -R/--remove -s/--recursive <pkgs>"
user_interfaces["pacman", "remove-packages-full,remove-orphans"]                                                    = "pmm -R/--remove -s/--recursive -n/--nosave <pkgs>"
user_interfaces["pacman", "update-package-database,update-file-database"]                                           = "pmm -S/--sync -y/--refresh"
user_interfaces["pacman", "update-package-database,upgrade-packages-partial"]                                       = ""
user_interfaces["pacman", "update-package-database,upgrade-packages-full"]                                          = ""
user_interfaces["pacman", "update-package-database,update-file-database,upgrade-packages-partial"]                  = ""
user_interfaces["pacman", "update-package-database,update-file-database,upgrade-packages-full"]                     = "pmm -S/--sync -y/--refresh -u/--sysupgrade"
user_interfaces["pacman", "update-package-database,install-packages"]                                               = ""
user_interfaces["pacman", "update-package-database,update-file-database,install-packages"]                          = "pmm -S/--sync -y/--refresh <pkgs>"
user_interfaces["pacman", "upgrade-packages-limited,install-packages"]                                              = ""
user_interfaces["pacman", "upgrade-packages-full,install-packages"]                                                 = "pmm -S/--sync -u/--sysupgrade <pkgs>"
user_interfaces["pacman", "update-package-database,upgrade-packages-partial,install-packages"]                      = ""
user_interfaces["pacman", "update-package-database,upgrade-packages-full,install-packages"]                         = ""
user_interfaces["pacman", "update-package-database,update-file-database,upgrade-packages-partial,install-packages"] = ""
user_interfaces["pacman", "update-package-database,update-file-database,upgrade-packages-full,install-packages"]    = "pmm -S/--sync -y/--refresh -u/--sysupgrade <pkgs>"

implementations["pacman", "clear-cache,remove-orphans"]                                                             = ""
implementations["pacman", "mark-packages-implicit,remove-orphans"]                                                  = ""
implementations["pacman", "remove-packages-limited,remove-orphans"]                                                 = "strat -r ${stratum} pacman ${flags} -Rs ${items}"
implementations["pacman", "remove-packages-full,remove-orphans"]                                                    = "strat -r ${stratum} pacman ${flags} -Rs ${items}"
implementations["pacman", "update-package-database,update-file-database"]                                           = "strat -r ${stratum} pacman ${flags} -Sy"
implementations["pacman", "update-package-database,upgrade-packages-partial"]                                       = "strat -r ${stratum} pacman ${flags} -Syu"
implementations["pacman", "update-package-database,upgrade-packages-full"]                                          = "strat -r ${stratum} pacman ${flags} -Syu"
implementations["pacman", "update-package-database,update-file-database,upgrade-packages-partial"]                  = "strat -r ${stratum} pacman ${flags} -Syu"
implementations["pacman", "update-package-database,update-file-database,upgrade-packages-full"]                     = "strat -r ${stratum} pacman ${flags} -Syu"
implementations["pacman", "update-package-database,install-packages"]                                               = "strat -r ${stratum} pacman ${flags} -Sy --asexplicit ${items}"
implementations["pacman", "update-package-database,update-file-database,install-packages"]                          = "strat -r ${stratum} pacman ${flags} -Sy --asexplicit ${items}"
implementations["pacman", "upgrade-packages-limited,install-packages"]                                              = "strat -r ${stratum} pacman ${flags} -Su --asexplicit ${items}"
implementations["pacman", "upgrade-packages-full,install-packages"]                                                 = "strat -r ${stratum} pacman ${flags} -Su --asexplicit ${items}"
implementations["pacman", "update-package-database,upgrade-packages-partial,install-packages"]                      = "strat -r ${stratum} pacman ${flags} -Syu --asexplicit ${items}"
implementations["pacman", "update-package-database,upgrade-packages-full,install-packages"]                         = "strat -r ${stratum} pacman ${flags} -Syu --asexplicit ${items}"
implementations["pacman", "update-package-database,update-file-database,upgrade-packages-partial,install-packages"] = "strat -r ${stratum} pacman ${flags} -Syu --asexplicit ${items}"
implementations["pacman", "update-package-database,update-file-database,upgrade-packages-full,install-packages"]    = "strat -r ${stratum} pacman ${flags} -Syu --asexplicit ${items}"

#
# Operations which have a standardized output format.
#
user_interfaces["pacman", "list-installed-package-files"] = "pmm -Q/--query -l/--list <pkgs>"
user_interfaces["pacman", "list-installed-explicit"]      = "pmm -Q/--query -e/--explicit"
user_interfaces["pacman", "list-installed-implicit"]      = "pmm -Q/--query -d/--deps"
user_interfaces["pacman", "list-installed-packages"]      = "pmm -Q/--query"
user_interfaces["pacman", "list-available-packages"]      = "pmm -S/--sync -l/--list"
user_interfaces["pacman", "search-for-package-by-name"]   = ""
user_interfaces["pacman", "search-for-package-by-all"]    = "pmm -S/--sync -s/--search <string>"
user_interfaces["pacman", "which-package-owns-file"]      = "pmm -Q/--query -o/--owns <file>"
user_interfaces["pacman", "which-packages-provide-file"]  = "pmm -F/--files <file>"

implementations["pacman", "list-installed-package-files"] = "strat -r ${stratum} pacman -Ql ${items} | cut -d' ' -f2-"
implementations["pacman", "list-installed-explicit"]      = "strat -r ${stratum} pacman -Qe | cut -d' ' -f1"
implementations["pacman", "list-installed-implicit"]      = "strat -r ${stratum} pacman -Qd | cut -d' ' -f1"
implementations["pacman", "list-installed-packages"]      = "strat -r ${stratum} pacman -Q | cut -d' ' -f1"
implementations["pacman", "list-available-packages"]      = "strat -r ${stratum} pacman -Sl | cut -d' ' -f2"
implementations["pacman", "search-for-package-by-name"]   = "strat -r ${stratum} pacman -Sl | cut -d' ' -f2 | grep ${items}"
implementations["pacman", "search-for-package-by-all"]    = "strat -r ${stratum} pacman -Ss ${items} | awk -F'[ /]' '/^[^ ]/{print$2}'"
implementations["pacman", "which-package-owns-file"]      = "strat -r ${stratum} pacman -Qo ${items} | awk '{print$(NF-1)}'"
implementations["pacman", "which-packages-provide-file"]  = "strat -r ${stratum} pacman -F ${items} |\
	awk '/^[^ ]/ {\
		split($(NF-1), a, \"/\");\
		print a[2]\"\t/\"$1\
	}'"

#
# Internal pmm operations.
#
implementations["pacman", "is-package-installed"]               = "strat -r ${stratum} pacman -Q ${items} >/dev/null 2>&1"
implementations["pacman", "is-package-available"]               = "strat -r ${stratum} pacman -Si ${items} >/dev/null 2>&1"
implementations["pacman", "is-file-db-available"]               = "true"
implementations["pacman", "print-file-db-install-instructions"] = ""
implementations["pacman", "print-package-version"]              = "strat -r ${stratum} pacman -Si ${items} |\
	awk '\
		$1 == \"Version\" {\
			sub(/[0-9]*:/, \"\", $3);\
			sub(/^[^0-9]/, \"\", $3);\
			sub(/[^0-9.].*/, \"\", $3);\
			sub(/[.]$/, \"\", $3);\
			print $3\
		}'"
implementations["pacman", "cache-package-db"]                   = "strat -r ${stratum} pacman -Sl |\
	awk '{\
		sub(/[0-9]*:/, \"\", $3);\
		sub(/^[^0-9]*/, \"\", $3);\
		sub(/[^0-9.].*/, \"\", $3);\
		sub(/[.]$/, \"\", $3);\
		print $2\"\t\"$3\
	}'"
