#!/bedrock/libexec/busybox awk -f
#
# Package Manager Manager yay support script
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2020 Daniel Thau <danthau@bedrocklinux.org>

#
# `yay -S --asexplicit` is used because `yay -S` retains
# explicit/implicit tracking on reinstalls.  Without `--asexplicit`, attempts
# to force a package to be explicitly installed by installing it would fail if
# it is already installed as a dependency.
#
# yay refuses to run as root.  ${unprivileged_user} wrapping is required for
# all calls.
#
# yay effectively supersedes pacman.  If both are in consideration for a given
# operation, pacman is dropped.
#

package_manager_canary_executables["yay"] = "yay"
supersedes["yay"] = "pacman"

#
# General, operation independent flags.
#
# Unlike operations, flags should not have implementations[].
#
user_interfaces["yay", "assume-no"]  = ""
user_interfaces["yay", "assume-yes"] = "--noconfirm"
user_interfaces["yay", "confirm"]    = ""
user_interfaces["yay", "quiet"]      = "-q/--quiet"
user_interfaces["yay", "verbose"]    = "-v/--verbose"

#
# Operations which directly forward the underlying command output.
#
user_interfaces["yay", "install-packages"]         = "pmm -S/--sync <pkgs>"
user_interfaces["yay", "reinstall-packages"]       = "" # not differentiated from install
user_interfaces["yay", "remove-packages-limited"]  = "pmm -R/--remove <pkgs>"
user_interfaces["yay", "remove-packages-full"]     = "pmm -R/--remove -n/--nosave <pkgs>"
user_interfaces["yay", "verify-packages"]          = "pmm -Q/--query -k/--check <pkgs>"
user_interfaces["yay", "verify-all-packages"]      = "pmm -Q/--query -k/--check"
user_interfaces["yay", "mark-packages-explicit"]   = "pmm -D/--database --asexplicit <pkgs>"
user_interfaces["yay", "mark-packages-implicit"]   = "pmm -D/--database --asdeps <pkgs>"
user_interfaces["yay", "show-package-information"] = "pmm -S/--sync -i/--info <pkgs>"
user_interfaces["yay", "clear-cache"]              = "pmm -S/--sync -c/--clean"
user_interfaces["yay", "remove-orphans"]           = "" # no user facing command
user_interfaces["yay", "update-package-database"]  = "pmm -S/--sync -y/--refresh"
user_interfaces["yay", "update-file-database"]     = "pmm -F/--files -y/--refresh"
user_interfaces["yay", "upgrade-packages-limited"] = "" # no partial upgrade concept
user_interfaces["yay", "upgrade-packages-full"]    = "pmm -S/--sync -u/--sysupgrade"

implementations["yay", "install-packages"]         = "${unprivileged_user} strat -r ${stratum} yay ${flags} -S --asexplicit ${items}"
implementations["yay", "reinstall-packages"]       = "${unprivileged_user} strat -r ${stratum} yay ${flags} -S ${items}"
implementations["yay", "remove-packages-limited"]  = "${unprivileged_user} strat -r ${stratum} yay ${flags} -R ${items}"
implementations["yay", "remove-packages-full"]     = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Rn ${items}"
implementations["yay", "verify-packages"]          = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Qk ${items}"
implementations["yay", "verify-all-packages"]      = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Qk"
implementations["yay", "mark-packages-explicit"]   = "${unprivileged_user} strat -r ${stratum} yay ${flags} -D --asexplicit ${items}"
implementations["yay", "mark-packages-implicit"]   = "${unprivileged_user} strat -r ${stratum} yay ${flags} -D --asdeps ${items}"
implementations["yay", "show-package-information"] = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Si ${items}"
implementations["yay", "clear-cache"]              = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Sc ${items}"
implementations["yay", "remove-orphans"]           = "! ${unprivileged_user} strat -r ${stratum} yay -Qdtq >/dev/null || ${unprivileged_user} strat -r ${stratum} yay -Qdtq | ${unprivileged_user} strat -r ${stratum} yay ${flags} -Rs -"
implementations["yay", "update-package-database"]  = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Sy"
implementations["yay", "update-file-database"]     = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Fy"
implementations["yay", "upgrade-packages-limited"] = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Su"
implementations["yay", "upgrade-packages-full"]    = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Su"

#
# Combine operations.
#
user_interfaces["yay", "clear-cache,remove-orphans"]                                                             = ""
user_interfaces["yay", "mark-packages-implicit,remove-orphans"]                                                  = ""
user_interfaces["yay", "remove-packages-limited,remove-orphans"]                                                 = "pmm -R/--remove -s/--recursive <pkgs>"
user_interfaces["yay", "remove-packages-full,remove-orphans"]                                                    = "pmm -R/--remove -s/--recursive -n/--nosave <pkgs>"
user_interfaces["yay", "update-package-database,update-file-database"]                                           = "pmm -S/--sync -y/--refresh"
user_interfaces["yay", "update-package-database,upgrade-packages-partial"]                                       = ""
user_interfaces["yay", "update-package-database,upgrade-packages-full"]                                          = ""
user_interfaces["yay", "update-package-database,update-file-database,upgrade-packages-partial"]                  = ""
user_interfaces["yay", "update-package-database,update-file-database,upgrade-packages-full"]                     = "pmm -S/--sync -y/--refresh -u/--sysupgrade"
user_interfaces["yay", "update-package-database,install-packages"]                                               = ""
user_interfaces["yay", "update-package-database,update-file-database,install-packages"]                          = "pmm -S/--sync -y/--refresh <pkgs>"
user_interfaces["yay", "upgrade-packages-limited,install-packages"]                                              = ""
user_interfaces["yay", "upgrade-packages-full,install-packages"]                                                 = "pmm -S/--sync -u/--sysupgrade <pkgs>"
user_interfaces["yay", "update-package-database,upgrade-packages-partial,install-packages"]                      = ""
user_interfaces["yay", "update-package-database,upgrade-packages-full,install-packages"]                         = ""
user_interfaces["yay", "update-package-database,update-file-database,upgrade-packages-partial,install-packages"] = ""
user_interfaces["yay", "update-package-database,update-file-database,upgrade-packages-full,install-packages"]    = ""

implementations["yay", "clear-cache,remove-orphans"]                                                             = ""
implementations["yay", "mark-packages-implicit,remove-orphans"]                                                  = ""
implementations["yay", "remove-packages-limited,remove-orphans"]                                                 = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Rs ${items}"
implementations["yay", "remove-packages-full,remove-orphans"]                                                    = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Rs ${items}"
implementations["yay", "update-package-database,update-file-database"]                                           = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Sy"
implementations["yay", "update-package-database,upgrade-packages-partial"]                                       = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Syu"
implementations["yay", "update-package-database,upgrade-packages-full"]                                          = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Syu"
implementations["yay", "update-package-database,update-file-database,upgrade-packages-partial"]                  = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Syu"
implementations["yay", "update-package-database,update-file-database,upgrade-packages-full"]                     = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Syu"
implementations["yay", "update-package-database,install-packages"]                                               = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Sy --asexplicit ${items}"
implementations["yay", "update-package-database,update-file-database,install-packages"]                          = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Sy --asexplicit ${items}"
implementations["yay", "upgrade-packages-limited,install-packages"]                                              = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Su --asexplicit ${items}"
implementations["yay", "upgrade-packages-full,install-packages"]                                                 = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Su --asexplicit ${items}"
implementations["yay", "update-package-database,upgrade-packages-partial,install-packages"]                      = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Syu --asexplicit ${items}"
implementations["yay", "update-package-database,upgrade-packages-full,install-packages"]                         = "${unprivileged_user} strat -r ${stratum} yay ${flags} -Syu --asexplicit ${items}"
implementations["yay", "update-package-database,update-file-database,upgrade-packages-partial,install-packages"] = ""
implementations["yay", "update-package-database,update-file-database,upgrade-packages-full,install-packages"]    = ""

#
# Operations which have a standardized output format.
#
user_interfaces["yay", "list-installed-package-files"] = "pmm -Q/--query -l/--list <pkgs>"
user_interfaces["yay", "list-installed-explicit"]      = "pmm -Q/--query -e/--explicit"
user_interfaces["yay", "list-installed-implicit"]      = "pmm -Q/--query -d/--deps"
user_interfaces["yay", "list-installed-packages"]      = "pmm -Q/--query"
user_interfaces["yay", "list-available-packages"]      = "pmm -S/--sync -l/--list"
user_interfaces["yay", "search-for-package-by-name"]   = ""
user_interfaces["yay", "search-for-package-by-all"]    = "pmm -S/--sync -s/--search <string>"
user_interfaces["yay", "which-package-owns-file"]      = "pmm -Q/--query -o/--owns <file>"
user_interfaces["yay", "which-packages-provide-file"]  = "pmm -F/--files <file>"

implementations["yay", "list-installed-package-files"] = "${unprivileged_user} strat -r ${stratum} yay -Ql ${items} | cut -d' ' -f2-"
implementations["yay", "list-installed-explicit"]      = "${unprivileged_user} strat -r ${stratum} yay -Qe | cut -d' ' -f1"
implementations["yay", "list-installed-implicit"]      = "${unprivileged_user} strat -r ${stratum} yay -Qd | cut -d' ' -f1"
implementations["yay", "list-installed-packages"]      = "${unprivileged_user} strat -r ${stratum} yay -Q | cut -d' ' -f1"
implementations["yay", "list-available-packages"]      = "${unprivileged_user} strat -r ${stratum} yay -Sl | cut -d' ' -f2"
implementations["yay", "search-for-package-by-name"]   = "${unprivileged_user} strat -r ${stratum} yay -Sl | cut -d' ' -f2 | grep ${items}"
implementations["yay", "search-for-package-by-all"]    = "${unprivileged_user} strat -r ${stratum} yay -Ss ${items} | awk -F'[ /]' '/^[^ ]/{print$2}'"
implementations["yay", "which-package-owns-file"]      = "${unprivileged_user} strat -r ${stratum} yay -Qo ${items} | awk '{print$(NF-1)}'"
implementations["yay", "which-packages-provide-file"]  = "${unprivileged_user} strat -r ${stratum} yay -F ${items} |\
	awk '/^[^ ]/ {\
		split($(NF-1), a, \"/\");\
		print a[2]\"\t/\"$1\
	}'"

#
# Internal pmm operations.
#
implementations["yay", "is-package-installed"]               = "${unprivileged_user} strat -r ${stratum} yay -Q ${items} >/dev/null 2>&1"
implementations["yay", "is-package-available"]               = "${unprivileged_user} strat -r ${stratum} yay -Si ${items} >/dev/null 2>&1"
implementations["yay", "is-file-db-available"]               = "true"
implementations["yay", "print-file-db-install-instructions"] = ""
implementations["yay", "print-package-version"]              = "${unprivileged_user} strat -r ${stratum} yay -Si ${items} |\
	awk '\
		$1 == \"Version\" {\
			sub(/[0-9]*:/, \"\", $3);\
			sub(/^[^0-9]/, \"\", $3);\
			sub(/[^0-9.].*/, \"\", $3);\
			sub(/[.]$/, \"\", $3);\
			print $3\
		}'"
implementations["yay", "cache-package-db"]                   = "${unprivileged_user} strat -r ${stratum} yay -Sl |\
	awk '$3 == \"unknown-version\" {\
		print $2\"\t0\"\
		next\
	}\
	{\
		sub(/[0-9]*:/, \"\", $3);\
		sub(/^[^0-9]*/, \"\", $3);\
		sub(/[^0-9.].*/, \"\", $3);\
		sub(/[.]$/, \"\", $3);\
		print $2\"\t\"$3\
	}'"
