#!/bin/sh
### Bedrock Linux 1.0alpha3 Bosco
### /etc/profile

# source settings from rc.conf
. /bedrock/etc/rc.conf

# these settings can be directly exported
export TZ
export LANG

# build the PATH
export PATH="/bedrock/bin:$NPATH:/bedrock/brpath/bin"
if [ "$(id -u)" = "0" ]
then
	export PATH="/bedrock/bin:/bedrock/sbin:$NPATH:$SPATH:/bedrock/brpath/bin:/bedrock/brpath/sbin"
fi
