#!/bin/sh
### Bedrock Linux 1.0beta1 Hawkey
### /etc/profile

# source settings from rc.conf
. /bedrock/etc/rc.conf

# these settings can be directly exported
export TZ
export LANG

# set the $*PATH variables
export PATH="/bedrock/bin:$NPATH:/bedrock/brpath/bin"
if [ "$(id -u)" = "0" ]
then
	export PATH="/bedrock/bin:/bedrock/sbin:$NPATH:$SPATH:/bedrock/brpath/bin:/bedrock/brpath/sbin"
fi
export MANPATH="$MANPATH:/bedrock/brpath/man"
export INFOPATH="$INFOPATH:/bedrock/brpath/info"
export XDG_DATA_DIRS="$XDG_DATA_DIRS:/bedrock/brpath"
