#!/bin/sh
### Bedrock Linux 1.0alpha4 Flopsie
### brp (BedRock Path)

# creates files which, when executed, will run a command in another client
# (through brc).

# source settings (specifically need NPATH and SPATH)
. /bedrock/etc/rc.conf

# check for need to print help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
cat <<EOF
Usage: brp [ARGUMENTS]

brp will make the commands from all of the clients available in
     /bedrock/brpath/{bin,sbin}
If these directories are in one's PATH (as should be done in /etc/profile for
Bedrock Linux already), one can simply run a command from another client as
though it was available locally.

Arguments:
   -a   only Add new commands; do not remove outdated ones. This will
		likely be faster.
   -p   Parallelize.  This will improve performance, but will not
		necessarily follow the client priorty order as specified in
		brp.conf.
EOF
	exit 0
fi

remove_existing(){
	if [ -n "$(ls $DIRECTORY)" ]
	then
		rm $DIRECTORY/*
	fi
}

create_bouncers(){
	for CLIENT in $(bri -l)
	do
		if [ ! -e /bedrock/brpath/clients/$CLIENT ]
		then
			(
				echo '#!/bin/sh'
				echo 'exec brc '"$CLIENT"' $(basename $0) "$@"'
			) > /bedrock/brpath/clients/$CLIENT
			chmod 755 /bedrock/brpath/clients/$CLIENT
		fi
	done
}

create_cmds_for_dir(){
	for EXECUTABLE in $(brc $1 ls $2 2>/dev/null)
	do
		if ! [ -e /bedrock/brpath/$3/$EXECUTABLE ]
		then
			ln -s /bedrock/brpath/clients/$1 /bedrock/brpath/$3/$EXECUTABLE 2>/dev/null
		fi
	done
}

create_cmds_for_client(){
	# create commands
	for DIRECTORY in $(echo $NPATH | sed 's/:/ /g')
	do
		create_cmds_for_dir $1 $DIRECTORY "bin" &
	done
	for DIRECTORY in $(echo $SPATH | sed 's/:/ /g')
	do
		create_cmds_for_dir $1 $DIRECTORY "sbin" &
	done
	wait
}

echo "Populating /bedrock/brpath/... "
# remove old items
if [ "$1" != "-a" ] && [ "$2" != "-a" ]
then
	for DIRECTORY in /bedrock/brpath/bin /bedrock/brpath/sbin /bedrock/brpath/clients
	do
		remove_existing &
	done
	# have to wait to ensure this finishes, or it will rm files created below
	wait
fi

# create bouncers
create_bouncers &

if [ "$1" != "-p" ] && [ "$2" != "-p" ]
then
	# loop over (enabled) clients in brp.conf in order
	parsed_clients=""
	for CLIENT in $(cat /bedrock/etc/brp.conf | sed '/^[ \t]*#/d')
	do
		if [ -r /bedrock/etc/clients.d/${CLIENT}.conf ]
		then
			parsed_clients="$parsed_clients $CLIENT "
			create_cmds_for_client $CLIENT
		fi
	done
	# loop over all clients and do any that were missing from brp.conf
	for CLIENT in $(bri -l)
	do
		if ! echo $parsed_clients | grep -q "$CLIENT"
		then
			create_cmds_for_client $CLIENT &
		fi
	done

else
	# parallelize here for performance even if order is not followed
	for CLIENT in $(bri -l)
	do
		create_cmds_for_client $CLIENT &
	done
fi
wait
echo "Completed populating /bedrock/brpath"
