#!/bin/sh

# This script will run the update commands specified in
# /opt/bedrock/etc/brclients.conf

# source settings and functions
. /opt/bedrock/etc/rc.conf
. /opt/bedrock/lib/brfunctions

# check for need to print help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
	echo "Usage: bru [CLIENT_NAMES]"
	echo ""
	echo "If the first argument is -y, bru will respond \"y\" to all prompts"
	echo "from update commands."
	echo ""
	echo "If given no arguments (other than a potential -y), bru will attempt"
	echo "to update all the clients.  Otherwise, it will attempt to update the"
	echo "clients given in the arguments."
	exit 0
fi

if [ "$1" = "-y" ]
then
	RESPOND_YES=/bin/true
	shift
else
	RESPOND_YES=/bin/false
fi

# ensure config file is available
if [ ! -r /opt/bedrock/etc/brclients.conf ]
then
	abort "Cannot read /opt/bedrock/etc/brclients.conf"
fi

# if given specific clients to update, ensure they are all present
for REQUESTED_CLIENT in $@
do
	if ! brc -l | grep -q $REQUESTED_CLIENT
	then
		abort "Cannot find \"$REQUESTED_CLIENT\" in /opt/bedrock/etc/brclients.conf"
	fi
done

CLIENT=""
OLDIFS="$IFS"
IFS='
'
for LINE in $(cat /opt/bedrock/etc/brclients.conf)
do
	IFS="$OLDIFS"
	if linegrep "^\[.\+\]$"
	then
		CLIENT=""
		if [ -z "$1" ]
		then
			CLIENT=$(linearg)
		else
			for REQUESTED_CLIENT in $@
			do
				if [ "$(linearg)" = "$REQUESTED_CLIENT" ]
				then
					CLIENT=$(linearg)
				fi
			done
		fi
		if [ ! -z "$CLIENT" ]
		then
			echo "bru: updating $CLIENT"
		fi
	elif linegrep "^update\s" && [ ! -z "$CLIENT" ]
	then
		if $RESPOND_YES
		then
			echo "Running and accepting everything from : $(linearg)"
			yes | brc $CLIENT $(linearg)
		else
			echo "Running: $(linearg)"
			brc $CLIENT $(linearg)
		fi
	fi
done
