#!/bin/sh
### Bedrock Linux 1.0alpha3 Bosco
### bru (BedRock Update)
# This script will run the update commands specified in
# /bedrock/etc/brclients.conf

# check for need to print help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
	echo "Usage: bru [ARGUMENT] [CLIENT_NAMES]"
	echo ""
	echo "bru can be used to update clients by running the updatecmd specified"
	echo "in /bedrock/etc/brclients.conf"
	echo ""
	echo "If ARGUMENT is -y, bru will respond \"y\" to all prompts"
	echo "from update commands."
	echo ""
	echo "If any CLIENT_NAMES are specified, bru will only update those"
	echo "clients.  If none are specified, bru will update all clients."
	exit 0
fi

# ensure config file is available
if [ ! -r /bedrock/etc/brclients.conf ]
then
	echo "Cannot read /bedrock/etc/brclients.conf" >&2
	exit 1
fi

# remove -y flag from $@
if [ "$1" = "-y" ]
then
	RESPOND_YES="/bin/true"
	shift
else
	RESPOND_YES="/bin/false"
fi

if [ -z $1 ]
then
	REQUESTED_CLIENTS="$(bri -l)"
else
	REQUESTED_CLIENTS="$@"
fi

# if given specific clients to update, ensure they are all present
for REQUESTED_CLIENT in $REQUESTED_CLIENTS
do
	if ! bri -l | grep -q $REQUESTED_CLIENT
	then
		echo "Cannot find \"$REQUESTED_CLIENT\" in /bedrock/etc/brclients.conf" >&2
		exit 1
	fi
done

# find updatecmd for each requested client and run it, piping "y" if
# requested.
CLIENT=""
OLDIFS="$IFS"
IFS='
'
for LINE in $(cat /bedrock/etc/brclients.conf)
do
	IFS="$OLDIFS"
	if echo $LINE | grep -q '^\[client ".*"\]$'
	then
		CLIENT=""
		POTENTIAL_CLIENT=$(echo $LINE | awk -F\" '{print$2}')
		for CURRENT_CLIENT in $REQUESTED_CLIENTS
		do
			if [ "$POTENTIAL_CLIENT" = "$CURRENT_CLIENT" ]
			then
				CLIENT="$POTENTIAL_CLIENT"
			fi
		done
	fi
	if echo $LINE | grep -q '^\s*updatecmd\s*=' && [ -n "$CLIENT" ]
	then
		UPDATECMD="$(echo $LINE | awk '{$1="";$2="";print$0}')"
		if $RESPOND_YES
		then
			UPDATECMD="yes | $UPDATECMD"
		fi
		echo "bru: updating $CLIENT"
		echo "running: $UPDATECMD"
		/bin/sh -c "$UPDATECMD"
	fi
	if echo $LINE | grep -q '^\s*framework\s*=' && [ -n "$CLIENT" ]
	then
		UPDATECMD=$(awk '
			/^\[framework ".*"\]$/{
				FRAMEWORK=substr($0,13,length($0)-14)
			}
			/^\[client ".*"\]$/{
				FRAMEWORK=""
			}
			/^[ \t]*updatecmd[ \t]*=/ && FRAMEWORK != ""{
				$1=""; $2=""
				print $0
				exit
			}
			' /bedrock/etc/brclients.conf)
		if $RESPOND_YES
		then
			UPDATECMD="yes | $UPDATECMD"
		fi
		echo "bru: updating $CLIENT"
		echo "running: $UPDATECMD"
		/bin/sh -c "$UPDATECMD"
	fi
done
