#!/bin/sh
### Bedrock Linux 1.0alpha3 Bosco
### poweroff wrapper
# ensures the core bedrock's poweroff is used, as a client's will probably not
# work.  This should be before the directory which contains a normal client's
# poweroff in the $PATH.
brc bedrock busybox poweroff $@
