#!/bin/sh
### Bedrock Linux 1.0beta1 Hawkey
### reboot wrapper
# ensures the core bedrock's reboot is used, as a client's will probably not
# work.  This should be before the directory which contains a normal client's
# reboot in the $PATH.
brc bedrock /bin/busybox reboot $@
