#!/bin/sh
### Bedrock Linux 1.0alpha3 Bosco
### shutdown wrapper
# Busybox does not seem to provide shutdown, and thus the core Bedrock does not
# have one.  A client's shutdown will probably not work either.  This script
# should catch an attempt to use shutdown and inform the user another,
# supported command should be used instead.  This should be before the
# directory which contains a normal client's shutdown in the $PATH.
echo 'ERROR: Bedrock Linux 1.0aphla3 Bosco does not support "shutdown".  Try'
echo 'halt, poweroff or reboot instead'
