#!/bedrock/libexec/busybox sh
#
# brl deref
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2018 Daniel Thau <danthau@bedrocklinux.org>
#
# Dereference stratum aliases.

. /bedrock/share/common-code

print_help() {
	printf "Usage: ${color_cmd}brl deref ${color_sub}[options] <strata>${color_norm}

Dereferences ${color_term}aliases${color_norm}.  Dereferencing a non-${color_term}alias${color_norm} ${color_term}stratum${color_norm} returns the ${color_term}stratum${color_norm}.

Options:
  ${color_cmd}-h${color_norm}, ${color_cmd}--help${color_norm}   print this message

Example:
  ${color_rcmd}# brl fetch fedora --release 27 --name fedora27
  ${color_rcmd}# brl fetch debian --release unstable --name sid
  ${color_rcmd}# brl alias fedora27 fedora
  ${color_rcmd}# brl alias sid unstable
  ${color_cmd}$ brl deref fedora
  ${color_strat}fedora27
  ${color_cmd}$ brl deref fedora27
  ${color_strat}fedora27
  ${color_cmd}$ brl deref unstable
  ${color_strat}sid
  ${color_cmd}$ brl deref sid
  ${color_strat}sid
${color_norm}"
}

handle_help "${@:-}"
min_args "${#}" "1"

for alias in "${@}"; do
	if ! is_stratum_or_alias "${alias}"; then
		abort "No stratum or alias called \"${alias}\"."
	elif ! stratum="$(deref "${alias}")"; then
		abort "Unable to dereference \"${alias}\"."
	else
		printf "${color_strat}%s${color_norm}\\n" "${stratum}"
	fi
done

exit_success
