#!/bedrock/libexec/busybox sh
#
# brl import
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2020-2026 Daniel Thau <danthau@bedrocklinux.org>
#
# Creates strata from specified file(s)

. /bedrock/share/common-code

print_help() {
	printf "Usage: ${color_cmd}brl import ${color_sub}<name> <source>${color_norm}

Creates a new ${color_term}stratum${color_norm} named ${color_sub}<name>${color_norm} from a specified
Requires root.
Some sources may require external tooling (e.g. ${color_cmd}qemu-img${color_norm}, ${color_cmd}vgscan${color_norm}, ${color_cmd}skopeo${color_norm}, etc)

Sources:
  Directory: ${color_sub}</path/to/directory>${color_norm}
  Tarball
    Uncompressed: ${color_sub}*${color_file}.tar${color_norm}
    gzip compressed: ${color_sub}*${color_file}.tar.gz${color_norm}
    bzip2 compressed: ${color_sub}*${color_file}.tar.bz2${color_norm}
    xz compressed: ${color_sub}*${color_file}.tar.xz${color_norm}
    zstd compressed; ${color_sub}*${color_file}.tar.zstd${color_norm}, ${color_sub}*${color_file}.tar.zst${color_norm}
  VM image
    Raw image: ${color_sub}*${color_file}.img${color_norm}
    Qemu image: ${color_sub}*${color_file}.qcow${color_norm}, ${color_sub}*${color_file}.qcow2${color_norm}, ${color_sub}*${color_file}.qcow3${color_norm}
    VirtualBox image: ${color_sub}*${color_file}.vdi${color_norm}
    VMware image: ${color_sub}*${color_file}.vmdk${color_norm}
  Container image
    docker: ${color_file}docker:${color_sub}*${color_norm}
    podman: ${color_file}podman:${color_sub}*${color_norm}

Example:
  ${color_cmd}$ wget http://example.com/arch-linux-root.tar.zst
  ${color_rcmd}# brl import arch ./arch-linux-root.tar.zst

  ${color_cmd}$ qemu-img create -f qcow3 disk.qcow3 10G
  ${color_cmd}$ qemu-system-x86_64 -drive file=disk.qcow3,if=virtio -cdrom ubuntu.iso # install in VM
  ${color_rcmd}# brl import ubuntu ./disk.qcow3

  ${color_cmd}$ podman pull quay.io/libpod/alpine:latest
  ${color_rcmd}# brl import alpine podman:quay.io/libpod/alpine:latest

  ${color_rcmd}# mkdir /mnt/laptop
  ${color_rcmd}# sshfs root@laptop:/ /mnt/laptop
  ${color_rcmd}# brl import laptop /mnt/laptop
${color_norm}"
}

import_abort() {
	printf "${color_alert}ERROR: %s\\n${color_norm}" "${@}" >&2

	notice "Cleaning up"
	backend_cleanup
	umount_r "${mnt}"
	less_lethal_rm_rf "${tgt}"

	exit 1
}

# Some virtual machines hide everything in an `@` directory
# Some directories/tarballs/etc contain an undesired parent directory
remove_redundant_root_dir() {
	if [ -d "${tgt}/@" ] && ls "${tgt}/@/"* >/dev/null 2>&1; then
		dir="${tgt}/@"
	elif [ "$(find "${tgt}" -mindepth 1 -maxdepth 1 | wc -l)" -ne 1 ]; then
		return
	elif ! [ -d "$(find "${tgt}" -mindepth 1 -maxdepth 1)" ]; then
		return
	else
		dir="$(find "${tgt}" -mindepth 1 -maxdepth 1)"
	fi
	find "${dir}" -mindepth 1 -maxdepth 1 -exec mv -- {} "${tgt}/" \;
	less_lethal_rm_rf "${dir}"
}

require_cmd() {
	cmd="${1}"
	if ! which "${cmd}" >/dev/null 2>&1; then
		abort "Specified source type requires \"${cmd}\" in \`\$PATH\`.  Install it and try again."
	fi
}

copy_dir_contents() {
	src="${1}"
	dst="${2}"

	mkdir -p "${dst}"
	count=$(find "${src}" -mindepth 1 -maxdepth 1 ! -name "brl-import" | wc -l)
	if [ "${count}" -eq 0 ]; then
		return 0
	fi
	find "${src}" -mindepth 1 -maxdepth 1 ! -name "brl-import" -exec cp -a -- {} "${dst}/" \; -exec echo x \; | progress_bar "${count}"
}

# Optionally implemented by back-ends to perform backend-specific cleanup
backend_cleanup() {
	true
}

handle_help "${@:-}"
min_args "${#}" "2"
name="${1}"
src="${2}"
tgt="/bedrock/strata/${name}/"
tmp="${tgt}/brl-import/"
mnt="${tmp}/mnt" # Expected temporary mount point; we'll unmount on unexpected error

backend_dir="/bedrock/share/brl-import/formats/"

require_root
lock
ensure_legal_stratum_name "${name}"
if is_stratum_or_alias "${name}"; then
	abort "Something already exists at \"/bedrock/strata/${name}\".  Either choose another name or remove preexisting stratum/alias with \`brl remove ${name}\` and try again."
fi

trap 'import_abort "Unexpected error occurred."' EXIT

mkdir -p "${tgt}" "${tmp}"

case "${src}" in
"-h" | "--help" | "help") print_help && exit 0;;
*.tar | *.tar.gz | *.tar.bz2 | *.tar.xz | *.tar.zst | *.tar.zstd) . "${backend_dir}/tarball" ;;
*.img | *.qcow | *.qcow2 | *.qcow3 | *.vmdk | *.vdi) . "${backend_dir}/vm-image" ;;
docker:* | podman:*) . "${backend_dir}/container" ;;
*)
	if [ -d "${src}" ]; then
		. "${backend_dir}/directory"
	else
		import_abort "Could not determine source type.  See --help."
	fi
	;;
esac

# defined by backend sourced above
import "${name}" "${src}" "${tgt}" "${tmp}" "${mnt}"

step "Cleaning up"
backend_cleanup
umount_r "${mnt}"
less_lethal_rm_rf "${tmp}"

step "Finalizing directory structure"
remove_redundant_root_dir

step "Importing users and groups"
import_users_and_groups "${tgt}/etc/passwd" "${tgt}/etc/group"

drop_lock

step "${color_term}Showing${color_norm}"
/bedrock/libexec/brl-show "${name}"

step "${color_term}Enabling${color_norm}"
/bedrock/libexec/brl-enable "${name}"

notice "Successfully ${color_term}imported${color_norm} ${color_strat}${name}${color_norm}"

exit_success
