#!/bedrock/libexec/busybox sh
#
# brl init
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2012-2018 Daniel Thau <danthau@bedrocklinux.org>
# Copyright (c) 2026 TheOddCell <me@oddcell.a>
#
# Choose which stratum should be used as the default init for simply the next reboot.

. /bedrock/share/common-code

print_help() {
	printf "Usage: ${color_cmd}brl init ${color_sub}[strat]${color_norm}

Choose which ${color_term}stratum${color_norm} the next reboot's init be.

Examples:
  ${color_cmd}$ brl init ${color_strat}arch${color_norm}:/lib/systemd/systemd # make the ${color_strat}arch${color_term} stratum ${color_norm}the next reboot's init, using /lib/systemd/systemd

  ${color_cmd}$ brl init ${color_strat}void${color_norm}:/sbin/init # make the ${color_strat}void${color_term} stratum ${color_norm}the next reboot's init, using /sbin/init

  ${color_cmd}$ brl init ${color_strat}debian${color_norm} # make the ${color_strat}debian${color_term} stratum ${color_norm}the next reboot's init, using /sbin/init

${color_norm}"
}

handle_help "${@:-}"
min_args "${#}" "1"

require_root
case "$1" in
  *:*)
    echo "$1">/bedrock/etc/tmpinit
    ;;
  *)
    echo "$1:/sbin/init">/bedrock/etc/tmpinit
    ;;
esac

notice "Please reboot manually to switch init systems."

exit_success
