#!/bin/sh

# This script will hash the commands from clients to make them available from
# other locations.

# source settings and functions
. /opt/bedrock/etc/rc.conf
. /opt/bedrock/lib/brfunctions


# check for need to print help
if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
	echo "Usage: brp [OPTIONS] [CLIENT_NAMES]"
	echo ""
	echo "Arguments:"
	echo "   -n   Only add new commands; do not remove outdated ones."
	echo "   -a   Run in all clients"
	echo ""
	echo "If given no arguments, brp will remove all current hashed commands in the"
	echo "current client (unless -n is given ) and create new ones from all other"
	echo "available clients.  If clients are given, brp will only add/remove commands"
	echo "from that specific client."
	exit 0
fi

# ensure config file is available
if [ ! -r /opt/bedrock/etc/brclients.conf ]
then
	abort "Cannot read /opt/bedrock/etc/brclients.conf"
fi

# get options out of $@ so $@ can be used for requested client list
APPEND_ONLY=/bin/false
ALL=/bin/false
for ARGUMENT in $@
do
	if [ "$ARGUMENT" = "-n" ]
	then
		APPEND_ONLY=/bin/false
		shift
	elif [ "$ARGUMENT" = "-a" ]
	then
		ALL=/bin/true
		shift
	fi
done
# if -a was given, use brl to run brp in all clients
if $ALL
then
	if $APPEND_ONLY
	then
		brl brp -n $@
	else
		brl brp $@
	fi
	exit
fi

# if given specific clients to hash, ensure they are all present
for REQUESTED_CLIENT in $@
do
	if ! brc -l | grep -q $REQUESTED_CLIENT
	then
		abort "Cannot find \"$REQUESTED_CLIENT\" in /opt/bedrock/etc/brclients.conf"
	fi
done

# ensure BRPATH exists
if [ ! -d "$BRPATH" ]
then
	if [ "$BR_CREATE_MISSING" -eq "1" ] && [ "$(id -u)" -eq "0" ]
	then
		echo "WARNING: \"$BRPATH\" not present, creating"
		mkdir "$BRPATH"
	else
		abort "Cannot find BRPATH: $BRPATH"
	fi
fi

if ! $APPEND_ONLY
then
	# remove old versions of commands
	echo -n "Removing old hashes... "
	if [ -z "$1" ] # remove from all clients
	then
		find $BRPATH -mindepth 1 -exec rm {} \;
	else # remove from specific clients
		for REQUESTED_CLIENT in "$@"
		do
			for FILE in $(find $BRPATH -mindepth 1)
			do
				if tail -n1 $FILE | cut -d" " -f2 | grep -q "^$REQUESTED_CLIENT$"
				then
					rm $FILE
				fi
			done
		done
	fi
	echo "done."
fi

# add new hashes
echo -n "Determining number of items..."
TOTAL=0
CLIENT=""
CLIENT_PATH=""
CURRENT_CLIENT="$(brw)"
AVAILABLE_CLIENTS="$(brc -l)"
while read LINE
do
	if linegrep "^\[.\+\]$"
	then
		CLIENT="$(linearg)"
		if [ "$CLIENT" = "$CURRENT_CLIENT" ]
		then
			CLIENT=""
		elif [ ! -z "$1" ] && ! echo "$@" | grep -q "^$CLIENT$"
		then
			CLIENT=""
		fi
	elif linegrep "^path\s" && [ ! -z "$CLIENT" ]
	then
		CLIENT_PATH=$(linearg)
		for DIRECTORY in /bin /usr/bin /usr/local/bin /sbin /usr/sbin /usr/local/sbin
		do
			if [ -d "$CLIENT_PATH$DIRECTORY" ]
			then
				TOTAL=$(expr $TOTAL + $(find $CLIENT_PATH$DIRECTORY | wc -l))
			fi
		done
	fi
done < /opt/bedrock/etc/brclients.conf
echo $TOTAL
COUNTER=0
while read LINE
do
	if linegrep "^\[.\+\]$"
	then
		CLIENT="$(linearg)"
		if [ "$CLIENT" = "$CURRENT_CLIENT" ]
		then
			CLIENT=""
		elif [ ! -z "$1" ] && ! echo "$@" | grep -q "^$CLIENT$"
		then
			CLIENT=""
		fi
	elif linegrep "^path\s" && [ ! -z "$CLIENT" ]
	then
		CLIENT_PATH=$(linearg)
		for DIRECTORY in /bin /usr/bin /usr/local/bin /sbin /usr/sbin /usr/local/sbin
		do
			if [ -d "$CLIENT_PATH$DIRECTORY" ]
			then
				cd $CLIENT_PATH
				for PROGRAM_PATH in echo $(find .$DIRECTORY -mindepth 1 | sed 's/^.//')
				do
					PROGRAM=$(basename $PROGRAM_PATH)
					if ! which $PROGRAM 1>/dev/null 2>/dev/null
					then
						echo "#!/bin/sh" > $BRPATH/$PROGRAM
						echo "/opt/bedrock/bin/brc $CLIENT $PROGRAM_PATH "'"$@"' >> $BRPATH/$PROGRAM
						chmod 555 $BRPATH/$PROGRAM
					fi
					COUNTER=$(expr $COUNTER + 1)
				done
			fi
			printf "Hashing commands... $(expr $COUNTER \* 100 / $TOTAL)%% [$COUNTER/$TOTAL]\r"
		done
	fi
done < /opt/bedrock/etc/brclients.conf
echo ""
