#!/bedrock/libexec/busybox sh
#
# KISS Linux bootstrap support
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2019-2020 Daniel Thau <danthau@bedrocklinux.org>
#

# shellcheck source=src/slash-bedrock/share/brl/backends/brl-fetch
. /bedrock/share/common-code
trap 'fetch_abort "Unexpected error occurred."' EXIT

check_supported() {
	false
}

speed_test_url() {
	echo "latest"
}

list_mirrors() {
	echo 'https://github.com/kisslinux/repo/releases'
}

brl_arch_to_distro() {
	case "${1}" in
	"x86_64") echo "x86_64" ;;
	*) abort "brl does not know how to translate arch \"${1}\" to ${distro} format" ;;
	esac
}

list_architectures() {
	cat <<EOF
x86_64
EOF
}

default_release() {
	wget -O- https://api.github.com/repos/kisslinux/repo/releases/latest 2>/dev/null | awk -F'"' '
	$2 == "assets" {
		in_assets = 1
	}
	/],/ && in_assets {
		in_assets = 0
	}
	$2 == "name" && !in_assets && $4 != "" {
		print$4
	}'
}

list_releases() {
	wget -O- https://api.github.com/repos/kisslinux/repo/releases 2>/dev/null | awk -F'"' '
	$2 == "assets" {
		in_assets = 1
	}
	/],/ && in_assets {
		in_assets = 0
	}
	$2 == "name" && !in_assets && $4 != "" {
		print$4
	}'
}

fetch() {
	prefix="https://github.com/kisslinux/repo/releases/download/"
	step "Downloading bootstrap software"
	wget -O "${bootstrap_dir}/checksum" "${prefix}/${target_release}/kiss-chroot.tar.xz.sha256"
	bootstrap_checksum="$(awk '{print$1}' "${bootstrap_dir}/checksum")"
	checksum_download "${cache}/bootstrap.tar.xz" "sha256sum" "${bootstrap_checksum}" "${prefix}/${target_release}/kiss-chroot.tar.xz"

	step "Preparing bootstrap software"
	tar -xv -f "${cache}/bootstrap.tar.xz" -C "${bootstrap_dir}" | awk 'NR%100==0' | progress_unknown
	mv "${bootstrap_dir}/kiss-chroot/"* "${target_dir}"
}
