#!/bin/sh
# This is a collection of functions to be sourced by Bedrock scripts.

# Abort current script, usually due to some detected error condition.
# Send argument (ie, error message) to sderr
abort(){
	echo $1 >&2
	exit 1
}

# Determines if argument is in $LINE, usually for detecting option in a bedrock
# config.
linegrep(){
	echo "$LINE" | grep -iq $1
}

# Bedrock's configuration file usually has some keyword followed by an
# argument.  For example, "path /var/chroot/bedrock".  Assuming the
# currently-being-parsed line is in $LINE, this returns the argument.  If the
# line is of the form "[TEXT]", it just returns "TEXT" - ie, it removes the
# brackets.
linearg(){
	if linegrep "^\[.\+\]$"
	then
		echo "$LINE" | sed 's/^\[\(.\+\)\]$/\1/'
	else
		echo "$LINE" | awk '{$1="";print}' | cut -c2-
	fi
}

