#!/bedrock/libexec/busybox sh
#
# Exherbo Linux bootstrap support
# Copyright 2019 Wulf C. Krueger <philantrop@exherbo.org>
# Distributed under the terms of the GNU General Public License v2
#
# based in part upon "Gentoo Linux bootstrap support" which is:
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
#	Copyright (c) 2016-2019 Daniel Thau <danthau@bedrocklinux.org>

# shellcheck source=src/slash-bedrock/libexec/brl-fetch
. /bedrock/share/common-code
trap 'fetch_abort "Unexpected error occurred."' EXIT

check_supported() {
	false
}

speed_test_url() {
	echo "/index.html"
}

list_mirrors() {
	echo "https://stages.exherbo.org"
}

brl_arch_to_distro() {
	case "${1}" in
	"aarch64") echo "aarch64" ;;
	"armv7hl") echo "armv7" ;;
	"x86_64") echo "x86_64" ;;
	*) abort "brl does not know how to translate arch \"${1}\" to ${distro} format" ;;
	esac
}

list_architectures() {
	cat <<EOF
aarch64
armv7hl
x86_64
EOF
}

default_release() {
	echo "rolling"
}

list_releases() {
	echo "rolling"
}

fetch() {
	paludis_builddir=/var/tmp/paludis/build
	paludis_user=paludisbuild
	paludis_group=paludisbuild

	case "${target_arch}" in
	"aarch64") url="${target_mirror}/aarch64-unknown-linux-gnueabi/exherbo-aarch64-unknown-linux-gnueabi-gcc-current.tar.xz" ;;
	"armv7hl") url="${target_mirror}/armv7-unknown-linux-gnueabihf/exherbo-armv7-unknown-linux-gnueabihf-gcc-current.tar.xz" ;;
	"x86_64") url="${target_mirror}/x86_64-pc-linux-gnu/exherbo-x86_64-pc-linux-gnu-gcc-current.tar.xz" ;;
	esac

	step "Downloading bootstrap software"
	download "${url}.sha256sum" "${bootstrap_dir}/sha256sum"
	sum="$(awk '{print$1}' "${bootstrap_dir}/sha256sum")"
	filename="$(echo "${url}" | awk -F/ '{print$NF}')"
	checksum_download "${cache}/${filename}" "sha256sum" "${sum}" "${url}"

	step "Preparing bootstrap software"
	tar xvJp -C "${bootstrap_dir}" -f "${cache}"/"${filename}" | awk 'NR%100==0' | progress_unknown

	step "Running bootstrap software"
	setup_chroot "${bootstrap_dir}"
	setup_ssl "${bootstrap_dir}"
	share_cache "." "${bootstrap_dir}/tarballs"
	chroot "${bootstrap_dir}" sh -c "cd /target-root && tar xvJpf /tarballs/${filename}" | awk 'NR%100==0' | progress_unknown

	step "Configuring"
	setup_chroot "${target_dir}"
	mkdir -p "${target_dir}/${paludis_builddir}/"
	chroot "${target_dir}" chown -R "${paludis_user}":"${paludis_group}" "${paludis_builddir}"
	chroot "${target_dir}" chmod -R g+rwx "${paludis_builddir}"
	chroot "${target_dir}" usermod -a -G "$(stat -c %G /dev/tty)" ${paludis_user}
}
