#!/bedrock/libexec/busybox sh
#
# openSUSE bootstrap support
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2016-2018 Daniel Thau <danthau@bedrocklinux.org>
#

. /bedrock/share/common-code
trap 'fetch_abort "Unexpected error occurred."' EXIT
check_supported() {
	false
}

check_experimental() {
	case "$(uname -m)" in
	"x86_64") true ;;
	*) false ;;
	esac
}

distro_arch_name() {
	case "$(uname -m)" in
	"x86_64") echo "x86_64" ;;
	*) fetch_abort "brl-fetch does not support distro/architecture pair" ;;
	esac
}

list_mirrors() {
	# from https://mirrors.opensuse.org/
	#
	#     The master download server, download.opensuse.org, automatically redirects you to a server near you
	#
	echo "https://download.opensuse.org"
}

speed_test_url() {
	echo "distribution/leap/42.3/repo/oss/suse/repodata/appdata-screenshots.tar"
}

#
# OpenSUSE 14 was named 42.  However, the following version went back 15.  For
# sorting purposes, place 42 where 14 would normally go.
#

list_releases() {
	wget -O- 'https://download.opensuse.org/distribution/leap/' 2>/dev/null |
		awk '/folder/,/<\/table>/' |
		list_links |
		grep '^[0-9][0-9.]*/$' |
		sed 's,/$,,' |
		sed 's/^42\>/14/' |
		sort -n |
		sed 's/^14\>/42/' |
		uniq
}

default_release() {
	list_releases |
		sed 's/^42\>/14/' |
		sort -n |
		sed 's/^14\>/42/' |
		tail -n1
}

fetch() {
	step_init 12

	if [ -z "${target_dir:-}" ]; then
		fetch_abort "Essential variable not set"
	fi

	step "Determining name"
	name="${flag_name:-${distro}}"
	notice "Using ${color_strat}${name}${color_norm}"

	step "Determining CPU architecture"
	arch="$(distro_arch_name)"
	notice "Using ${color_file}${arch}${color_norm}"

	step "Determining release"
	release="${flag_release:-$(default_release)}"
	notice "Using ${color_file}${release}${color_norm}"

	step "Determining mirror"
	mirror="$(pick_mirror "$(speed_test_url)")"
	notice "Using ${color_link}${mirror}${color_norm}"

	step "Making directory structure"
	bootstrap_dir="${target_dir}/brl-bootstrap"
	mkdir -p "${target_dir}" "${bootstrap_dir}/target-root"

	step "Downloading package information database"
	url="$(find_link "${mirror}/distribution/leap/${release}/repo/oss/repodata/" "primary.xml.gz")"
	wget -O "${bootstrap_dir}/primary.xml.gz" "${url}"
	gunzip "${bootstrap_dir}/primary.xml.gz"

	step "Converting distro package information database to brl format"
	rpmdb_to_brldb "${bootstrap_dir}/primary.xml" "${bootstrap_dir}/brldb"

	step "Calculating required bootstrap packages"
	brldb_calculate_paths_with_deps "${bootstrap_dir}/brldb" "${bootstrap_dir}/package_paths" "zypper rpm openSUSE-release filesystem ca-certificates ca-certificates-cacert"

	step "Downloading bootstrap packages"
	download_files "${bootstrap_dir}" "$(awk -v"m=${mirror}/distribution/leap/${release}/repo/oss/" '{print m"/"$0}' "${bootstrap_dir}/package_paths")"

	step "Extracting bootstrap packages"
	# This round is just to bootstrap the distro's rpm.
	# Next step we'll use the distro's rpm to install everything properly.
	# Need to extract filesystem first to ensure symlinks are set up
	extract_rpms "${bootstrap_dir}" "${bootstrap_dir}"/filesystem*.rpm "${bootstrap_dir}"/*.rpm

	step "Installing bootstrap packages"
	setup_chroot "${bootstrap_dir}"
	LC_ALL=C chroot "${bootstrap_dir}" rpm -i ./*.rpm 2>&1 | progress_unknown

	step "Running bootstrap software"
	mount --bind "${target_dir}" "${bootstrap_dir}/target-root"
	chroot "${bootstrap_dir}" rpm -i --root=/target-root --nodeps openSUSE-release-*.rpm
	chroot "${bootstrap_dir}" zypper --non-interactive --root=/target-root ar -f "http://download.opensuse.org/distribution/leap/${release}/repo/oss/" repo-oss
	chroot "${bootstrap_dir}" zypper --non-interactive --root=/target-root ar -f "http://download.opensuse.org/update/leap/${release}/oss/" update-oss
	chroot "${bootstrap_dir}" zypper --non-interactive --gpg-auto-import-keys --root=/target-root refresh
	chroot "${bootstrap_dir}" zypper --non-interactive --gpg-auto-import-keys --root=/target-root install -f zypper rpm openSUSE-release filesystem ca-certificates ca-certificates-cacert

	# Some pre/post install hooks do not seem to take from the bootstrap environment.  Need to be installed in the environment proper.
	setup_chroot "${target_dir}"
	chroot "${target_dir}" zypper --non-interactive ar -f "http://download.opensuse.org/distribution/leap/${release}/repo/oss/" repo-oss || true
	chroot "${target_dir}" zypper --non-interactive ar -f "http://download.opensuse.org/update/leap/${release}/oss/" update-oss || true
	chroot "${target_dir}" zypper --non-interactive --gpg-auto-import-keys refresh
	chroot "${target_dir}" zypper --non-interactive --gpg-auto-import-keys install -f zypper rpm openSUSE-release filesystem ca-certificates ca-certificates-cacert
	tear_down_chroot "${target_dir}"

	step "Removing temporary bootstrap files"
	less_lethal_rm_rf "${bootstrap_dir}"

	notice "Successfully acquired ${distro} stratum"
}
