#!/bedrock/libexec/busybox sh
#
# Parabola GNU/Linux-libre bootstrap support
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2016-2020 Daniel Thau <danthau@bedrocklinux.org>
#

# shellcheck source=src/slash-bedrock/libexec/brl-fetch
. /bedrock/share/common-code
trap 'fetch_abort "Unexpected error occurred."' EXIT

check_supported() {
	false
}

speed_test_url() {
	echo "core/os/${distro_arch}/core.db.tar.gz"
}

list_mirrors() {
	mirror_list_url='https://www.parabola.nu/mirrorlist/all/'
	wget -O- "${mirror_list_url}" 2>/dev/null |
		awk -F "[ $]" ' /^#Server/ {print$3} '
}

brl_arch_to_distro() {
	case "${1}" in
	"armv7hl") echo "armv7h" ;;
	"i686") echo "i686" ;;
	"ppc64le") echo "ppc64le" ;;
	"x86_64") echo "x86_64" ;;
	*) abort "brl does not know how to translate arch \"${1}\" to ${distro} format" ;;
	esac
}

list_architectures() {
	cat <<EOF
armv7hl
i686
ppc64le
x86_64
EOF
}

default_release() {
	echo "rolling"
}

list_releases() {
	echo "rolling"
}

setup_pacman() {
	# Remove auto architecture detection, as it will confuse things like
	# i686 on an x86_64 box and armv7hl on a aarch64 box.
	#
	# Also remove CheckSpace, which sometimes gets confused by Bedrock's
	# mount setup.
	sed 's/^Architecture[ \t]*=.*$//' "${1}/etc/pacman.conf" |
		awk -v"a=${distro_arch}" '{print} $0 == "[options]" {print "Architecture = "a}' |
		sed 's/^[ \t]*CheckSpace/# &/' \
			>"${1}/etc/pacman.conf-new"
	mv "${1}/etc/pacman.conf-new" "${1}/etc/pacman.conf"

	LC_ALL=C chroot "${1}" /usr/bin/update-ca-trust
	LC_ALL=C chroot "${1}" /usr/bin/pacman-key --init
	LC_ALL=C chroot "${1}" /usr/bin/pacman-key --populate archlinux archlinux32 archlinuxarm parabola
	LC_ALL=C chroot "${1}" /usr/bin/pacman-key --refresh-keys

	if ! grep -q "^Server" "${1}/etc/pacman.d/mirrorlist"; then
		echo "### Set by Bedrock Linux when acquiring this stratum" >>"${1}/etc/pacman.d/mirrorlist"
		echo "Server = ${target_mirror}/\$repo/os/\$arch" >>"$1/etc/pacman.d/mirrorlist"
	fi
}

fetch() {
	bootstrap_deps="arch-install-scripts"

	step "Downloading package information database"
	wget -O "${bootstrap_dir}/core.db.tar.gz" "${target_mirror}/core/os/${distro_arch}/core.db.tar.gz"
	wget -O "${bootstrap_dir}/extra.db.tar.gz" "${target_mirror}/extra/os/${distro_arch}/extra.db.tar.gz"
	wget -O "${bootstrap_dir}/libre.db.tar.gz" "${target_mirror}/libre/os/${distro_arch}/libre.db.tar.gz"

	step "Decompressing package information database"
	mkdir -p "${bootstrap_dir}/pacmandb/core" "${bootstrap_dir}/pacmandb/extra" "${bootstrap_dir}/pacmandb/libre"
	(
		tar -xv -f "${bootstrap_dir}/core.db.tar.gz" -C "${bootstrap_dir}/pacmandb/core/"
		tar -xv -f "${bootstrap_dir}/extra.db.tar.gz" -C "${bootstrap_dir}/pacmandb/extra/"
		tar -xv -f "${bootstrap_dir}/libre.db.tar.gz" -C "${bootstrap_dir}/pacmandb/libre/"
	) | awk 'NR%100==0' | progress_unknown

	step "Converting distro package information database to brl format"
	pacmandb_to_brldb "${bootstrap_dir}/pacmandb" "${bootstrap_dir}/brldb"

	step "Calculating required bootstrap packages"
	brldb_calculate_required_packages "${bootstrap_dir}/brldb" "${bootstrap_dir}/required_packages" "${bootstrap_deps}"

	step "Downloading bootstrap packages"
	# brldb contains repo/filename
	# files are at mirror/repo/os/arch/filename
	checksum_downloads "${cache}/packages/" "$(awk -v"a=${distro_arch}" -v"m=${target_mirror}" '{sub("/", "/os/"a"/"); print m"/"$0}' "${bootstrap_dir}/required_packages")"

	step "Extracting bootstrap packages"
	bootstrap_packages="$(awk -v"d=${cache}/packages/" '{sub(/^.*\//,d);print $1}' "${bootstrap_dir}/required_packages")"
	# shellcheck disable=SC2086
	extract_pacman_pkgs "${bootstrap_dir}" ${bootstrap_packages}

	step "Running bootstrap software"
	# pacstrap mounts devtmpfs (which is shared with the host system) and
	# chowns files in it based on /etc/passwd and /etc/group.  Ensure
	# system copies of files are used to avoid problematic file ownership
	# change in /dev.
	mkdir -p "${target_dir}/etc"
	cp -a "/etc/passwd" "${target_dir}/etc/passwd"
	cp -a "/etc/group" "${target_dir}/etc/group"

	setup_chroot "${bootstrap_dir}"
	setup_pacman "${bootstrap_dir}"
	share_cache "packages" "${bootstrap_dir}/target-root/var/cache/pacman/pkg/"
	LC_ALL=C chroot "${bootstrap_dir}" pacstrap "/target-root" base

	step "Configuring"
	setup_chroot "${target_dir}"
	setup_pacman "${target_dir}"
	cp "${cache}/packages/"* "${target_dir}/var/cache/pacman/"
	if LC_ALL=C chroot "${target_dir}" pacman -Q linux >/dev/null 2>&1; then
		LC_ALL=C chroot "${target_dir}" pacman --noconfirm -R linux
	fi
}
