#!/bedrock/libexec/busybox sh
#
# Void Linux (musl) bootstrap support
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2016-2019 Daniel Thau <danthau@bedrocklinux.org>
#

. /bedrock/share/common-code
trap 'fetch_abort "Unexpected error occurred."' EXIT

check_supported() {
	true
}

speed_test_url() {
	echo "static/sha256sums.txt"
}

list_mirrors() {
	mirror_list_url='https://voidlinux.org/download/'
	wget -O- "${mirror_list_url}" 2>/dev/null |
		awk '/id="tier-1-mirrors"/,/<\/ul>/' |
		awk '-F[<>()]' '{print$3}' |
		grep "^http" |
		sed 's, ,,'
}

brl_arch_to_distro() {
	# while static mips/mipsel xbps shows up in the mirrors, the mirrors
	# do not provide binary packages for it.
	case "${1}" in
	"aarch64") echo "aarch64" ;;
	"x86_64") echo "x86_64" ;;
	*) abort "brl does not know how to translate arch \"${1}\" to ${distro:-} format" ;;
	esac
}

list_architectures() {
	cat <<EOF
aarch64
x86_64
EOF
}

default_release() {
	echo "rolling"
}

list_releases() {
	echo "rolling"
}

fetch() {
	step "Downloading bootstrap software"
	url="$(find_link "${target_mirror:-}/static/" "^xbps-static-latest[.]${distro_arch:-}-musl[.]tar[.]xz")"
	wget -O "${bootstrap_dir:-}/xbps-static.tar.xz" "${url}"

	step "Preparing bootstrap software"
	(
		cd "${bootstrap_dir:-}"
		tar xf xbps-static.tar.xz
	)

	case "${distro_arch:-}" in
	x86_64 | i686) distro_mirror="${target_mirror:-}/current/musl" ;;
	*) distro_mirror="${target_mirror:-}/current/${distro_arch:-}" ;;
	esac

	step "Running bootstrap software"
	set +o pipefail
	yes "" | LC_ALL=C XBPS_ARCH="${distro_arch:-}-musl" "${bootstrap_dir:-}/usr/bin/xbps-install" -S -R "${distro_mirror}" -r "${target_dir:-}" base-voidstrap
	set -o pipefail

	step "Configuring"
	if [ -d "${target_dir:-}/usr/share/xbps.d/" ]; then
		echo "repository=${distro_mirror}" >>"${target_dir:-}/usr/share/xbps.d/00-brl-fetch.conf"
	fi
	# Void's zsh package does not create /etc/zsh/zshenv but it is needed
	# for various Bedrock hooks
	if ! [ -e "${target_dir:-}/etc/zsh/zshenv" ]; then
		mkdir -p "${target_dir:-}/etc/zsh/"
		echo "# File created by Bedrock Linux during stratum fetch" >"${target_dir:-}/etc/zsh/zshenv"
	fi
}
