#!/bedrock/libexec/busybox sh
#
# brl version
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      version 2 as published by the Free Software Foundation.
#
# Copyright (c) 2016-2018 Daniel Thau <danthau@bedrocklinux.org>
#
# brl help::6::3::Query ${color_bedrock}Bedrock Linux${color_norm} version
#
# Prints current install's Bedrock Linux version

. /bedrock/share/common-code

print_help() {
	printf "Usage: ${color_cmd}brl version ${color_sub}[options]${color_norm}

Prints ${color_bedrock}Bedrock Linux${color_norm} install's version.

Options:
  ${color_cmd}-h${color_norm}, ${color_cmd}--help${color_norm}   print this message

Examples:
  ${color_cmd}$ brl version
  ${color_norm}Bedrock Linux 0.7.0 Poki
${color_norm}"
}

handle_help "${@:-}"

cat /bedrock/etc/bedrock-release

exit_success
